# yaml-language-server: $schema=https://raw.githubusercontent.com/compose-spec/compose-spec/master/schema/compose-spec.json

name: "word-game"
services:
  app:
    build: "."
    environment:
      NODE_ENV:
    env_file:
      - ".env"
      - ".env.${NODE_ENV}"
      - path: ".env.${NODE_ENV}.local"
        required: false
    ports:
      - name: "main"
        host_ip: "127.0.0.1"
        target: "${PORT}"
