# yaml-language-server: $schema=https://raw.githubusercontent.com/compose-spec/compose-spec/master/schema/compose-spec.json

configs:
  initdb:
    file: "./db/init.sql"
name: "word-game"
networks:
  default:
    attachable: true
secrets:
  app:
    file: "/mnt/efs/word-game/secrets/.env.app"
  migration:
    file: "/mnt/efs/word-game/secrets/.env.migration"
services:
  app:
    deploy:
      endpoint_mode: "dnsrr"
      restart_policy:
        delay: "10s"
        max_attempts: 3
        window: "1m"
    extends:
      file: "docker-compose.yml"
      service: "app"
  db:
    deploy:
      endpoint_mode: "dnsrr"
      restart_policy:
        delay: "5s"
        max_attempts: 3
        window: "1m"
    extends:
      file: "docker-compose.yml"
      service: "db"
volumes:
  db:
    driver: "local"
    driver_opts:
      device: "/mnt/efs/word-game/data"
      o: "bind"
      type: "none"
