# yaml-language-server: $schema=https://raw.githubusercontent.com/compose-spec/compose-spec/master/schema/compose-spec.json
name: "word-game"
services:
  app:
    build:
      context: "."
    environment:
      NODE_ENV: "development"
    env_file:
      - ".env"
      - ".env.$NODE_ENV"
      - ".env.$NODE_ENV.local"
    ports:
      - "$PORT:$PORT"
