# yaml-language-server: $schema=https://raw.githubusercontent.com/compose-spec/compose-spec/master/schema/compose-spec.json

name: "word-game"
services:
  app:
    deploy:
      endpoint_mode: vip
      mode: "global"
    extends:
      file: "docker-compose.yml"
      service: "app"
    init: true
    ports:
      - "${PORT}"
