# yaml-language-server: $schema=https://raw.githubusercontent.com/compose-spec/compose-spec/master/schema/compose-spec.json

name: "word-game"
services:
  app:
    environment:
      NODE_ENV:
    env_file:
      - ".env"
      - ".env.${NODE_ENV}"
      - path: ".env.${NODE_ENV}.local"
        required: false
    image: "localhost:5000/word-game-app"
