# yaml-language-server: $schema=https://raw.githubusercontent.com/compose-spec/compose-spec/master/schema/compose-spec.json

name: "word-game"
services:
  app:
    extends:
      file: "docker-compose.yml"
      service: "app"
  db:
    extends:
      file: "docker-compose.yml"
      service: "db"
volumes:
  db:
    driver: "local"
    driver_opts:
      device: "/mnt/efs/word-game/db"
      o: "bind"
      type: "none"
    name: "word-game_db"
