# yaml-language-server: $schema=https://raw.githubusercontent.com/compose-spec/compose-spec/master/schema/compose-spec.json

configs:
  initdb:
    file: "../db/init.sql"
name: "word-game"
services:
  app-dev:
    build: {}
    depends_on:
      - "db"
    environment:
      NODE_ENV: "development"
    init: true
    volumes:
      - source: ".."
        target: "/home/node/app"
        type: "bind"
  db:
    extends:
      file: "../docker-compose.yml"
      service: "db"
volumes:
  db:
